before:
  hooks:
    - make test
builds:

  # This is not really needed, but its here if we need to back the binary in the executor which
  # we don't at the moment and goreleaser requires that we specify at least one build.
  # Actual binary will be published using a different goreleaser config
  - dir: ./task/bq2bq
    main: .
    id: "bq2bq"
    binary: "optimus-task-bq2bq_{{.Version}}_{{.Os}}_{{.Arch}}"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Image=docker.io/odpf/optimus-task-bq2bq
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
release:
  disable: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/odpf/optimus-task-bq2bq-executor:latest"
      - "docker.io/odpf/optimus-task-bq2bq-executor:{{ .Version }}"
    dockerfile: ./task/bq2bq/executor/Dockerfile
    extra_files:
      - task/bq2bq/executor
